import {
  tablerChevronDown as erpChevronDownOutline,
  tablerChevronLeft as erpChevronStartOutline,
  tablerChevronRight as erpChevronEndOutline,
  tablerChevronUp as erpChevronUpOutline,
  tablerBuildings as erpBranchesOutline,
  tablerBuilding as erpBuildingOutline,
  tablerCheck as erpCheckMarkOutline,
  tablerX as erpDismissOutline,
  tablerCopy as erpCopyOutline,
  tablerUser as erpCustomerOutline,
  tablerLayoutGrid as erpDashboardOutline,
  tablerTrash as erpDeleteOutline,
  tablerEye as erpEyeOutline,
  tablerEyeOff as erpEyeOffOutline,
  tablerPackage as erpInventoryOutline,
  tablerStack as erpLayersOutline,
  tablerMapPin as erpLocationOutline,
  tablerLogin as erpLoginOutline,
  tablerLogout as erpLogoutOutline,
  tablerList as erpMenuOutline,
  tablerMoon as erpMoonOutline,
  tablerBell as erpNotificationOutline,
  tablerBriefcase as erpOperationsOutline,
  tablerUsers as erpPeopleOutline,
  tablerPhone as erpPhoneOutline,
  tablerPhoneCall as erpPhoneCallOutline,
  tablerPrinter as erpPrintOutline,
  tablerServer as erpServerOutline,
  tablerSettings as erpSettingsOutline,
  tablerShieldCheck as erpShieldCheckOutline,
  tablerSun as erpSunOutline,
  tablerUser as erpUserOutline,
  tablerWallet as erpWalletOutline,
  tablerAlertTriangle as erpWarningOutline,
  tablerWifiOff as erpWifiOffOutline,
  tablerPencil as erpEditOutline,
  tablerDeviceFloppy as erpSaveOutline,
  tablerUpload as erpUploadOutline,
  tablerDownload as erpDownloadOutline,
  tablerSortAscending as erpSortAscendingOutline,
  tablerSortDescending as erpSortDescendingOutline,
  tablerListNumbers as erpSourceOrderOutline,
  tablerGenderMale as erpMaleOutline,
  tablerGenderFemale as erpFemaleOutline,
  tablerDots as erpMoreHorizontalOutline,
  tablerDotsVertical as erpMoreVerticalOutline,
  tablerCalendar as erpCalendarOutline,
  tablerClock as erpClockOutline,
  tablerLock as erpLockOutline,
  tablerLockOpen as erpUnlockOutline,
  tablerFile as erpFileOutline,
  tablerFolder as erpFolderOutline,
  tablerPaperclip as erpAttachmentOutline,
  tablerExternalLink as erpExternalLinkOutline,
  tablerHistory as erpHistoryOutline,
  tablerArrowBackUp as erpUndoOutline,
  tablerArrowForwardUp as erpRedoOutline,
  tablerPlus as erpPlusOutline,
  tablerMinus as erpMinusOutline,
} from '@ng-icons/tabler-icons';
import {
  lucidePlusCircle as erpAddOutline,
  lucideCheckCircle as erpCheckOutline,
  lucideXCircle as erpCloseOutline,
  lucideXCircle as erpErrorOutline,
  lucideHandshake as erpHandshakeOutline,
  lucideHouse as erpHomeOutline,
  lucideInfo as erpInfoOutline,
  lucideWrench as erpMaintenanceOutline,
  lucideHandCoins as erpMoneyOutline,
  lucideRefreshCw as erpRefreshOutline,
  lucideUserLock as erpSecurityOutline,
  lucideSkipBack as erpSkipStartOutline,
  lucideSkipForward as erpSkipEndOutline,
  lucideCheckCircle as erpSuccessOutline,
  lucideFunnel as erpFilterOutline,
} from '@ng-icons/lucide';
import {
  heroMagnifyingGlass as erpSearchOutline,
  heroEnvelope as erpMailOutline,
  heroQuestionMarkCircle as erpHelpOutline,
} from '@ng-icons/heroicons/outline';
import {
  phosphorPlusCircleFill as erpAddFilled,
  phosphorBuildingsFill as erpBranchesFilled,
  phosphorBuildingFill as erpBuildingFilled,
  phosphorCheckCircleFill as erpCheckFilled,
  phosphorCheckFill as erpCheckMarkFilled,
  phosphorXCircleFill as erpCloseFilled,
  phosphorXFill as erpDismissFilled,
  phosphorCopyFill as erpCopyFilled,
  phosphorSquaresFourFill as erpDashboardFilled,
  phosphorXCircleFill as erpErrorFilled,
  phosphorHandshakeFill as erpHandshakeFilled,
  phosphorHouseFill as erpHomeFilled,
  phosphorInfoFill as erpInfoFilled,
  phosphorPackageFill as erpInventoryFilled,
  phosphorSignInFill as erpLoginFilled,
  phosphorSignOutFill as erpLogoutFilled,
  phosphorWrenchFill as erpMaintenanceFilled,
  phosphorListFill as erpMenuFilled,
  phosphorHandCoinsFill as erpMoneyFilled,
  phosphorUsersFill as erpPeopleFilled,
  phosphorPhoneCallFill as erpPhoneCallFilled,
  phosphorPrinterFill as erpPrintFilled,
  phosphorArrowsClockwiseFill as erpRefreshFilled,
  phosphorGearFill as erpSettingsFilled,
  phosphorSkipBackFill as erpSkipStartFilled,
  phosphorSkipForwardFill as erpSkipEndFilled,
  phosphorCheckCircleFill as erpSuccessFilled,
  phosphorWalletFill as erpWalletFilled,
  phosphorWarningFill as erpWarningFilled,
  phosphorPencilSimpleFill as erpEditFilled,
  phosphorFloppyDiskFill as erpSaveFilled,
  phosphorUploadSimpleFill as erpUploadFilled,
  phosphorDownloadSimpleFill as erpDownloadFilled,
  phosphorFunnelFill as erpFilterFilled,
  phosphorSortAscendingFill as erpSortAscendingFilled,
  phosphorSortDescendingFill as erpSortDescendingFilled,
  phosphorListNumbersFill as erpSourceOrderFilled,
  phosphorGenderMaleFill as erpMaleFilled,
  phosphorGenderFemaleFill as erpFemaleFilled,
  phosphorDotsThreeFill as erpMoreHorizontalFilled,
  phosphorDotsThreeVerticalFill as erpMoreVerticalFilled,
  phosphorCalendarBlankFill as erpCalendarFilled,
  phosphorLockOpenFill as erpUnlockFilled,
  phosphorEnvelopeSimpleFill as erpMailFilled,
  phosphorPaperclipFill as erpAttachmentFilled,
  phosphorArrowSquareOutFill as erpExternalLinkFilled,
  phosphorQuestionFill as erpHelpFilled,
  phosphorClockCounterClockwiseFill as erpHistoryFilled,
  phosphorArrowUUpLeftFill as erpUndoFilled,
  phosphorArrowUUpRightFill as erpRedoFilled,
  phosphorPlusFill as erpPlusFilled,
  phosphorMinusFill as erpMinusFilled,
} from '@ng-icons/phosphor-icons/fill';
import {
  tablerUserFill as erpCustomerFilled,
  tablerTrashFill as erpDeleteFilled,
  tablerEyeFill as erpEyeFilled,
  tablerStackFill as erpLayersFilled,
  tablerMapPinFill as erpLocationFilled,
  tablerMoonFill as erpMoonFilled,
  tablerBellFill as erpNotificationFilled,
  tablerBriefcaseFill as erpOperationsFilled,
  tablerPhoneFill as erpPhoneFilled,
  tablerShieldLockFill as erpSecurityFilled,
  tablerShieldCheckFill as erpShieldCheckFilled,
  tablerSunFill as erpSunFilled,
  tablerUserFill as erpUserFilled,
  tablerClockFill as erpClockFilled,
  tablerLockFill as erpLockFilled,
  tablerFileFill as erpFileFilled,
  tablerFolderFill as erpFolderFilled,
} from '@ng-icons/tabler-icons/fill';
import {
  heroChevronDownSolid as erpChevronDownFilled,
  heroChevronLeftSolid as erpChevronStartFilled,
  heroChevronRightSolid as erpChevronEndFilled,
  heroChevronUpSolid as erpChevronUpFilled,
  heroMagnifyingGlassSolid as erpSearchFilled,
  heroServerSolid as erpServerFilled,
} from '@ng-icons/heroicons/solid';
import {
  fluentEyeOffFilled as erpEyeOffFilled,
  fluentWifiOffFilled as erpWifiOffFilled,
} from '@ng-icons/fluent-ui/filled';
import {ErpIconName} from './icon-contracts';

export interface ErpIconDefinition {
  readonly outlineSvg: string;
  readonly filledSvg: string;
  readonly mirrorInRtl: boolean;
}

export const ERP_ICON_REGISTRY: Readonly<Record<ErpIconName, ErpIconDefinition>> = {
  'add': {
    outlineSvg: erpAddOutline,
    filledSvg: erpAddFilled,
    mirrorInRtl: false,
  },
  'chevron-down': {
    outlineSvg: erpChevronDownOutline,
    filledSvg: erpChevronDownFilled,
    mirrorInRtl: false,
  },
  'chevron-start': {
    outlineSvg: erpChevronStartOutline,
    filledSvg: erpChevronStartFilled,
    mirrorInRtl: true,
  },
  'chevron-end': {
    outlineSvg: erpChevronEndOutline,
    filledSvg: erpChevronEndFilled,
    mirrorInRtl: true,
  },
  'chevron-up': {
    outlineSvg: erpChevronUpOutline,
    filledSvg: erpChevronUpFilled,
    mirrorInRtl: false,
  },
  'branches': {
    outlineSvg: erpBranchesOutline,
    filledSvg: erpBranchesFilled,
    mirrorInRtl: false,
  },
  'building': {
    outlineSvg: erpBuildingOutline,
    filledSvg: erpBuildingFilled,
    mirrorInRtl: false,
  },
  'check': {
    outlineSvg: erpCheckOutline,
    filledSvg: erpCheckFilled,
    mirrorInRtl: false,
  },
  'check-mark': {
    outlineSvg: erpCheckMarkOutline,
    filledSvg: erpCheckMarkFilled,
    mirrorInRtl: false,
  },
  'close': {
    outlineSvg: erpCloseOutline,
    filledSvg: erpCloseFilled,
    mirrorInRtl: false,
  },
  'dismiss': {
    outlineSvg: erpDismissOutline,
    filledSvg: erpDismissFilled,
    mirrorInRtl: false,
  },
  'copy': {
    outlineSvg: erpCopyOutline,
    filledSvg: erpCopyFilled,
    mirrorInRtl: false,
  },
  'customer': {
    outlineSvg: erpCustomerOutline,
    filledSvg: erpCustomerFilled,
    mirrorInRtl: false,
  },
  'dashboard': {
    outlineSvg: erpDashboardOutline,
    filledSvg: erpDashboardFilled,
    mirrorInRtl: false,
  },
  'delete': {
    outlineSvg: erpDeleteOutline,
    filledSvg: erpDeleteFilled,
    mirrorInRtl: false,
  },
  'error': {
    outlineSvg: erpErrorOutline,
    filledSvg: erpErrorFilled,
    mirrorInRtl: false,
  },
  'eye': {
    outlineSvg: erpEyeOutline,
    filledSvg: erpEyeFilled,
    mirrorInRtl: false,
  },
  'eye-off': {
    outlineSvg: erpEyeOffOutline,
    filledSvg: erpEyeOffFilled,
    mirrorInRtl: false,
  },
  'handshake': {
    outlineSvg: erpHandshakeOutline,
    filledSvg: erpHandshakeFilled,
    mirrorInRtl: false,
  },
  'home': {
    outlineSvg: erpHomeOutline,
    filledSvg: erpHomeFilled,
    mirrorInRtl: false,
  },
  'info': {
    outlineSvg: erpInfoOutline,
    filledSvg: erpInfoFilled,
    mirrorInRtl: false,
  },
  'inventory': {
    outlineSvg: erpInventoryOutline,
    filledSvg: erpInventoryFilled,
    mirrorInRtl: false,
  },
  'layers': {
    outlineSvg: erpLayersOutline,
    filledSvg: erpLayersFilled,
    mirrorInRtl: false,
  },
  'location': {
    outlineSvg: erpLocationOutline,
    filledSvg: erpLocationFilled,
    mirrorInRtl: false,
  },
  'login': {
    outlineSvg: erpLoginOutline,
    filledSvg: erpLoginFilled,
    mirrorInRtl: true,
  },
  'logout': {
    outlineSvg: erpLogoutOutline,
    filledSvg: erpLogoutFilled,
    mirrorInRtl: true,
  },
  'maintenance': {
    outlineSvg: erpMaintenanceOutline,
    filledSvg: erpMaintenanceFilled,
    mirrorInRtl: false,
  },
  'menu': {
    outlineSvg: erpMenuOutline,
    filledSvg: erpMenuFilled,
    mirrorInRtl: false,
  },
  'money': {
    outlineSvg: erpMoneyOutline,
    filledSvg: erpMoneyFilled,
    mirrorInRtl: false,
  },
  'moon': {
    outlineSvg: erpMoonOutline,
    filledSvg: erpMoonFilled,
    mirrorInRtl: false,
  },
  'notification': {
    outlineSvg: erpNotificationOutline,
    filledSvg: erpNotificationFilled,
    mirrorInRtl: false,
  },
  'operations': {
    outlineSvg: erpOperationsOutline,
    filledSvg: erpOperationsFilled,
    mirrorInRtl: false,
  },
  'people': {
    outlineSvg: erpPeopleOutline,
    filledSvg: erpPeopleFilled,
    mirrorInRtl: false,
  },
  'phone': {
    outlineSvg: erpPhoneOutline,
    filledSvg: erpPhoneFilled,
    mirrorInRtl: false,
  },
  'phone-call': {
    outlineSvg: erpPhoneCallOutline,
    filledSvg: erpPhoneCallFilled,
    mirrorInRtl: false,
  },
  'print': {
    outlineSvg: erpPrintOutline,
    filledSvg: erpPrintFilled,
    mirrorInRtl: false,
  },
  'refresh': {
    outlineSvg: erpRefreshOutline,
    filledSvg: erpRefreshFilled,
    mirrorInRtl: false,
  },
  'search': {
    outlineSvg: erpSearchOutline,
    filledSvg: erpSearchFilled,
    mirrorInRtl: false,
  },
  'security': {
    outlineSvg: erpSecurityOutline,
    filledSvg: erpSecurityFilled,
    mirrorInRtl: false,
  },
  'server': {
    outlineSvg: erpServerOutline,
    filledSvg: erpServerFilled,
    mirrorInRtl: false,
  },
  'settings': {
    outlineSvg: erpSettingsOutline,
    filledSvg: erpSettingsFilled,
    mirrorInRtl: false,
  },
  'shield-check': {
    outlineSvg: erpShieldCheckOutline,
    filledSvg: erpShieldCheckFilled,
    mirrorInRtl: false,
  },
  'skip-start': {
    outlineSvg: erpSkipStartOutline,
    filledSvg: erpSkipStartFilled,
    mirrorInRtl: true,
  },
  'skip-end': {
    outlineSvg: erpSkipEndOutline,
    filledSvg: erpSkipEndFilled,
    mirrorInRtl: true,
  },
  'success': {
    outlineSvg: erpSuccessOutline,
    filledSvg: erpSuccessFilled,
    mirrorInRtl: false,
  },
  'sun': {
    outlineSvg: erpSunOutline,
    filledSvg: erpSunFilled,
    mirrorInRtl: false,
  },
  'user': {
    outlineSvg: erpUserOutline,
    filledSvg: erpUserFilled,
    mirrorInRtl: false,
  },
  'wallet': {
    outlineSvg: erpWalletOutline,
    filledSvg: erpWalletFilled,
    mirrorInRtl: false,
  },
  'warning': {
    outlineSvg: erpWarningOutline,
    filledSvg: erpWarningFilled,
    mirrorInRtl: false,
  },
  'wifi-off': {
    outlineSvg: erpWifiOffOutline,
    filledSvg: erpWifiOffFilled,
    mirrorInRtl: false,
  },
  'edit': {
    outlineSvg: erpEditOutline,
    filledSvg: erpEditFilled,
    mirrorInRtl: false,
  },
  'save': {
    outlineSvg: erpSaveOutline,
    filledSvg: erpSaveFilled,
    mirrorInRtl: false,
  },
  'upload': {
    outlineSvg: erpUploadOutline,
    filledSvg: erpUploadFilled,
    mirrorInRtl: false,
  },
  'download': {
    outlineSvg: erpDownloadOutline,
    filledSvg: erpDownloadFilled,
    mirrorInRtl: false,
  },
  'filter': {
    outlineSvg: erpFilterOutline,
    filledSvg: erpFilterFilled,
    mirrorInRtl: false,
  },
  'sort-ascending': {
    outlineSvg: erpSortAscendingOutline,
    filledSvg: erpSortAscendingFilled,
    mirrorInRtl: false,
  },
  'sort-descending': {
    outlineSvg: erpSortDescendingOutline,
    filledSvg: erpSortDescendingFilled,
    mirrorInRtl: false,
  },
  'source-order': {
    outlineSvg: erpSourceOrderOutline,
    filledSvg: erpSourceOrderFilled,
    mirrorInRtl: false,
  },
  'male': {
    outlineSvg: erpMaleOutline,
    filledSvg: erpMaleFilled,
    mirrorInRtl: false,
  },
  'female': {
    outlineSvg: erpFemaleOutline,
    filledSvg: erpFemaleFilled,
    mirrorInRtl: false,
  },
  'more-horizontal': {
    outlineSvg: erpMoreHorizontalOutline,
    filledSvg: erpMoreHorizontalFilled,
    mirrorInRtl: false,
  },
  'more-vertical': {
    outlineSvg: erpMoreVerticalOutline,
    filledSvg: erpMoreVerticalFilled,
    mirrorInRtl: false,
  },
  'calendar': {
    outlineSvg: erpCalendarOutline,
    filledSvg: erpCalendarFilled,
    mirrorInRtl: false,
  },
  'clock': {
    outlineSvg: erpClockOutline,
    filledSvg: erpClockFilled,
    mirrorInRtl: false,
  },
  'lock': {
    outlineSvg: erpLockOutline,
    filledSvg: erpLockFilled,
    mirrorInRtl: false,
  },
  'unlock': {
    outlineSvg: erpUnlockOutline,
    filledSvg: erpUnlockFilled,
    mirrorInRtl: false,
  },
  'mail': {
    outlineSvg: erpMailOutline,
    filledSvg: erpMailFilled,
    mirrorInRtl: false,
  },
  'file': {
    outlineSvg: erpFileOutline,
    filledSvg: erpFileFilled,
    mirrorInRtl: false,
  },
  'folder': {
    outlineSvg: erpFolderOutline,
    filledSvg: erpFolderFilled,
    mirrorInRtl: false,
  },
  'attachment': {
    outlineSvg: erpAttachmentOutline,
    filledSvg: erpAttachmentFilled,
    mirrorInRtl: false,
  },
  'external-link': {
    outlineSvg: erpExternalLinkOutline,
    filledSvg: erpExternalLinkFilled,
    mirrorInRtl: false,
  },
  'help': {
    outlineSvg: erpHelpOutline,
    filledSvg: erpHelpFilled,
    mirrorInRtl: false,
  },
  'history': {
    outlineSvg: erpHistoryOutline,
    filledSvg: erpHistoryFilled,
    mirrorInRtl: false,
  },
  'undo': {
    outlineSvg: erpUndoOutline,
    filledSvg: erpUndoFilled,
    mirrorInRtl: false,
  },
  'redo': {
    outlineSvg: erpRedoOutline,
    filledSvg: erpRedoFilled,
    mirrorInRtl: false,
  },
  'plus': {
    outlineSvg: erpPlusOutline,
    filledSvg: erpPlusFilled,
    mirrorInRtl: false,
  },
  'minus': {
    outlineSvg: erpMinusOutline,
    filledSvg: erpMinusFilled,
    mirrorInRtl: false,
  },
};
