import {
  tablerChevronDown as erpChevronDownOutline,
  tablerChevronLeft as erpChevronStartOutline,
  tablerChevronRight as erpChevronEndOutline,
  tablerChevronUp as erpChevronUpOutline,
  tablerBuildings as erpBranchesOutline,
  tablerBuilding as erpBuildingOutline,
  tablerCopy as erpCopyOutline,
  tablerUser as erpCustomerOutline,
  tablerLayoutGrid as erpDashboardOutline,
  tablerTrash as erpDeleteOutline,
  tablerEye as erpEyeOutline,
  tablerEyeOff as erpEyeOffOutline,
  tablerPackage as erpInventoryOutline,
  tablerStack as erpLayersOutline,
  tablerMapPin as erpLocationOutline,
  tablerLogin as erpLoginOutline,
  tablerLogout as erpLogoutOutline,
  tablerList as erpMenuOutline,
  tablerMoon as erpMoonOutline,
  tablerBell as erpNotificationOutline,
  tablerBriefcase as erpOperationsOutline,
  tablerUsers as erpPeopleOutline,
  tablerPhone as erpPhoneOutline,
  tablerPhoneCall as erpPhoneCallOutline,
  tablerPrinter as erpPrintOutline,
  tablerServer as erpServerOutline,
  tablerSettings as erpSettingsOutline,
  tablerShieldCheck as erpShieldCheckOutline,
  tablerSun as erpSunOutline,
  tablerUser as erpUserOutline,
  tablerWallet as erpWalletOutline,
  tablerAlertTriangle as erpWarningOutline,
  tablerWifiOff as erpWifiOffOutline,
  tablerPencil as erpEditOutline,
  tablerDeviceFloppy as erpSaveOutline,
  tablerUpload as erpUploadOutline,
  tablerDownload as erpDownloadOutline,
  tablerSortAscending as erpSortAscendingOutline,
  tablerSortDescending as erpSortDescendingOutline,
  tablerDots as erpMoreHorizontalOutline,
  tablerDotsVertical as erpMoreVerticalOutline,
  tablerCalendar as erpCalendarOutline,
  tablerClock as erpClockOutline,
  tablerLock as erpLockOutline,
  tablerLockOpen as erpUnlockOutline,
  tablerFile as erpFileOutline,
  tablerFolder as erpFolderOutline,
  tablerPaperclip as erpAttachmentOutline,
  tablerExternalLink as erpExternalLinkOutline,
  tablerHistory as erpHistoryOutline,
  tablerArrowBackUp as erpUndoOutline,
  tablerArrowForwardUp as erpRedoOutline,
  tablerPlus as erpPlusOutline,
  tablerMinus as erpMinusOutline,
} from '@ng-icons/tabler-icons';
import {
  lucidePlusCircle as erpAddOutline,
  lucideCheckCircle as erpCheckOutline,
  lucideXCircle as erpCloseOutline,
  lucideXCircle as erpErrorOutline,
  lucideHandshake as erpHandshakeOutline,
  lucideHouse as erpHomeOutline,
  lucideInfo as erpInfoOutline,
  lucideWrench as erpMaintenanceOutline,
  lucideHandCoins as erpMoneyOutline,
  lucideRefreshCw as erpRefreshOutline,
  lucideUserLock as erpSecurityOutline,
  lucideSkipBack as erpSkipStartOutline,
  lucideSkipForward as erpSkipEndOutline,
  lucideCheckCircle as erpSuccessOutline,
  lucideFunnel as erpFilterOutline,
} from '@ng-icons/lucide';
import {
  heroMagnifyingGlass as erpSearchOutline,
  heroEnvelope as erpMailOutline,
  heroQuestionMarkCircle as erpHelpOutline,
} from '@ng-icons/heroicons/outline';
import {
  tablerUserFill as erpCustomerFilled,
  tablerLayoutGridFill as erpDashboardFilled,
  tablerTrashFill as erpDeleteFilled,
  tablerEyeFill as erpEyeFilled,
  tablerHomeFill as erpHomeFilled,
  tablerStackFill as erpLayersFilled,
  tablerMapPinFill as erpLocationFilled,
  tablerMoonFill as erpMoonFilled,
  tablerBellFill as erpNotificationFilled,
  tablerBriefcaseFill as erpOperationsFilled,
  tablerPhoneFill as erpPhoneFilled,
  tablerShieldLockFill as erpSecurityFilled,
  tablerSettingsFill as erpSettingsFilled,
  tablerShieldCheckFill as erpShieldCheckFilled,
  tablerSunFill as erpSunFilled,
  tablerUserFill as erpUserFilled,
  tablerCalendarFill as erpCalendarFilled,
  tablerClockFill as erpClockFilled,
  tablerLockFill as erpLockFilled,
  tablerFileFill as erpFileFilled,
  tablerFolderFill as erpFolderFilled,
} from '@ng-icons/tabler-icons/fill';
import {
  heroPlusCircleSolid as erpAddFilled,
  heroChevronDownSolid as erpChevronDownFilled,
  heroChevronLeftSolid as erpChevronStartFilled,
  heroChevronRightSolid as erpChevronEndFilled,
  heroChevronUpSolid as erpChevronUpFilled,
  heroCheckCircleSolid as erpCheckFilled,
  heroXCircleSolid as erpCloseFilled,
  heroXCircleSolid as erpErrorFilled,
  heroArrowRightOnRectangleSolid as erpLoginFilled,
  heroWrenchSolid as erpMaintenanceFilled,
  heroUsersSolid as erpPeopleFilled,
  heroPrinterSolid as erpPrintFilled,
  heroMagnifyingGlassSolid as erpSearchFilled,
  heroServerSolid as erpServerFilled,
  heroCheckCircleSolid as erpSuccessFilled,
  heroWalletSolid as erpWalletFilled,
  heroPencilSolid as erpEditFilled,
  heroArrowUpTraySolid as erpUploadFilled,
  heroArrowDownTraySolid as erpDownloadFilled,
  heroFunnelSolid as erpFilterFilled,
  heroBarsArrowUpSolid as erpSortAscendingFilled,
  heroBarsArrowDownSolid as erpSortDescendingFilled,
  heroLockOpenSolid as erpUnlockFilled,
  heroEnvelopeSolid as erpMailFilled,
  heroPaperClipSolid as erpAttachmentFilled,
  heroArrowTopRightOnSquareSolid as erpExternalLinkFilled,
  heroArrowUturnLeftSolid as erpUndoFilled,
  heroArrowUturnRightSolid as erpRedoFilled,
  heroPlusSolid as erpPlusFilled,
  heroMinusSolid as erpMinusFilled,
} from '@ng-icons/heroicons/solid';
import {
  fluentBuildingMultipleFilled as erpBranchesFilled,
  fluentBuildingFilled as erpBuildingFilled,
  fluentCopyFilled as erpCopyFilled,
  fluentEyeOffFilled as erpEyeOffFilled,
  fluentHandshakeFilled as erpHandshakeFilled,
  fluentInfoFilled as erpInfoFilled,
  fluentBoxFilled as erpInventoryFilled,
  fluentSignOutFilled as erpLogoutFilled,
  fluentListFilled as erpMenuFilled,
  fluentMoneyHandFilled as erpMoneyFilled,
  fluentCallFilled as erpPhoneCallFilled,
  fluentArrowSyncFilled as erpRefreshFilled,
  fluentPreviousFilled as erpSkipStartFilled,
  fluentNextFilled as erpSkipEndFilled,
  fluentWarningFilled as erpWarningFilled,
  fluentWifiOffFilled as erpWifiOffFilled,
  fluentSaveFilled as erpSaveFilled,
  fluentMoreHorizontalFilled as erpMoreHorizontalFilled,
  fluentMoreVerticalFilled as erpMoreVerticalFilled,
  fluentQuestionFilled as erpHelpFilled,
  fluentHistoryFilled as erpHistoryFilled,
} from '@ng-icons/fluent-ui/filled';
import {ErpIconName} from './icon-contracts';

export interface ErpIconDefinition {
  readonly outlineSvg: string;
  readonly filledSvg: string;
  readonly mirrorInRtl: boolean;
}

export const ERP_ICON_REGISTRY: Readonly<Record<ErpIconName, ErpIconDefinition>> = {
  'add': {
    outlineSvg: erpAddOutline,
    filledSvg: erpAddFilled,
    mirrorInRtl: false,
  },
  'chevron-down': {
    outlineSvg: erpChevronDownOutline,
    filledSvg: erpChevronDownFilled,
    mirrorInRtl: false,
  },
  'chevron-start': {
    outlineSvg: erpChevronStartOutline,
    filledSvg: erpChevronStartFilled,
    mirrorInRtl: true,
  },
  'chevron-end': {
    outlineSvg: erpChevronEndOutline,
    filledSvg: erpChevronEndFilled,
    mirrorInRtl: true,
  },
  'chevron-up': {
    outlineSvg: erpChevronUpOutline,
    filledSvg: erpChevronUpFilled,
    mirrorInRtl: false,
  },
  'branches': {
    outlineSvg: erpBranchesOutline,
    filledSvg: erpBranchesFilled,
    mirrorInRtl: false,
  },
  'building': {
    outlineSvg: erpBuildingOutline,
    filledSvg: erpBuildingFilled,
    mirrorInRtl: false,
  },
  'check': {
    outlineSvg: erpCheckOutline,
    filledSvg: erpCheckFilled,
    mirrorInRtl: false,
  },
  'close': {
    outlineSvg: erpCloseOutline,
    filledSvg: erpCloseFilled,
    mirrorInRtl: false,
  },
  'copy': {
    outlineSvg: erpCopyOutline,
    filledSvg: erpCopyFilled,
    mirrorInRtl: false,
  },
  'customer': {
    outlineSvg: erpCustomerOutline,
    filledSvg: erpCustomerFilled,
    mirrorInRtl: false,
  },
  'dashboard': {
    outlineSvg: erpDashboardOutline,
    filledSvg: erpDashboardFilled,
    mirrorInRtl: false,
  },
  'delete': {
    outlineSvg: erpDeleteOutline,
    filledSvg: erpDeleteFilled,
    mirrorInRtl: false,
  },
  'error': {
    outlineSvg: erpErrorOutline,
    filledSvg: erpErrorFilled,
    mirrorInRtl: false,
  },
  'eye': {
    outlineSvg: erpEyeOutline,
    filledSvg: erpEyeFilled,
    mirrorInRtl: false,
  },
  'eye-off': {
    outlineSvg: erpEyeOffOutline,
    filledSvg: erpEyeOffFilled,
    mirrorInRtl: false,
  },
  'handshake': {
    outlineSvg: erpHandshakeOutline,
    filledSvg: erpHandshakeFilled,
    mirrorInRtl: false,
  },
  'home': {
    outlineSvg: erpHomeOutline,
    filledSvg: erpHomeFilled,
    mirrorInRtl: false,
  },
  'info': {
    outlineSvg: erpInfoOutline,
    filledSvg: erpInfoFilled,
    mirrorInRtl: false,
  },
  'inventory': {
    outlineSvg: erpInventoryOutline,
    filledSvg: erpInventoryFilled,
    mirrorInRtl: false,
  },
  'layers': {
    outlineSvg: erpLayersOutline,
    filledSvg: erpLayersFilled,
    mirrorInRtl: false,
  },
  'location': {
    outlineSvg: erpLocationOutline,
    filledSvg: erpLocationFilled,
    mirrorInRtl: false,
  },
  'login': {
    outlineSvg: erpLoginOutline,
    filledSvg: erpLoginFilled,
    mirrorInRtl: true,
  },
  'logout': {
    outlineSvg: erpLogoutOutline,
    filledSvg: erpLogoutFilled,
    mirrorInRtl: true,
  },
  'maintenance': {
    outlineSvg: erpMaintenanceOutline,
    filledSvg: erpMaintenanceFilled,
    mirrorInRtl: false,
  },
  'menu': {
    outlineSvg: erpMenuOutline,
    filledSvg: erpMenuFilled,
    mirrorInRtl: false,
  },
  'money': {
    outlineSvg: erpMoneyOutline,
    filledSvg: erpMoneyFilled,
    mirrorInRtl: false,
  },
  'moon': {
    outlineSvg: erpMoonOutline,
    filledSvg: erpMoonFilled,
    mirrorInRtl: false,
  },
  'notification': {
    outlineSvg: erpNotificationOutline,
    filledSvg: erpNotificationFilled,
    mirrorInRtl: false,
  },
  'operations': {
    outlineSvg: erpOperationsOutline,
    filledSvg: erpOperationsFilled,
    mirrorInRtl: false,
  },
  'people': {
    outlineSvg: erpPeopleOutline,
    filledSvg: erpPeopleFilled,
    mirrorInRtl: false,
  },
  'phone': {
    outlineSvg: erpPhoneOutline,
    filledSvg: erpPhoneFilled,
    mirrorInRtl: false,
  },
  'phone-call': {
    outlineSvg: erpPhoneCallOutline,
    filledSvg: erpPhoneCallFilled,
    mirrorInRtl: false,
  },
  'print': {
    outlineSvg: erpPrintOutline,
    filledSvg: erpPrintFilled,
    mirrorInRtl: false,
  },
  'refresh': {
    outlineSvg: erpRefreshOutline,
    filledSvg: erpRefreshFilled,
    mirrorInRtl: false,
  },
  'search': {
    outlineSvg: erpSearchOutline,
    filledSvg: erpSearchFilled,
    mirrorInRtl: false,
  },
  'security': {
    outlineSvg: erpSecurityOutline,
    filledSvg: erpSecurityFilled,
    mirrorInRtl: false,
  },
  'server': {
    outlineSvg: erpServerOutline,
    filledSvg: erpServerFilled,
    mirrorInRtl: false,
  },
  'settings': {
    outlineSvg: erpSettingsOutline,
    filledSvg: erpSettingsFilled,
    mirrorInRtl: false,
  },
  'shield-check': {
    outlineSvg: erpShieldCheckOutline,
    filledSvg: erpShieldCheckFilled,
    mirrorInRtl: false,
  },
  'skip-start': {
    outlineSvg: erpSkipStartOutline,
    filledSvg: erpSkipStartFilled,
    mirrorInRtl: true,
  },
  'skip-end': {
    outlineSvg: erpSkipEndOutline,
    filledSvg: erpSkipEndFilled,
    mirrorInRtl: true,
  },
  'success': {
    outlineSvg: erpSuccessOutline,
    filledSvg: erpSuccessFilled,
    mirrorInRtl: false,
  },
  'sun': {
    outlineSvg: erpSunOutline,
    filledSvg: erpSunFilled,
    mirrorInRtl: false,
  },
  'user': {
    outlineSvg: erpUserOutline,
    filledSvg: erpUserFilled,
    mirrorInRtl: false,
  },
  'wallet': {
    outlineSvg: erpWalletOutline,
    filledSvg: erpWalletFilled,
    mirrorInRtl: false,
  },
  'warning': {
    outlineSvg: erpWarningOutline,
    filledSvg: erpWarningFilled,
    mirrorInRtl: false,
  },
  'wifi-off': {
    outlineSvg: erpWifiOffOutline,
    filledSvg: erpWifiOffFilled,
    mirrorInRtl: false,
  },
  'edit': {
    outlineSvg: erpEditOutline,
    filledSvg: erpEditFilled,
    mirrorInRtl: false,
  },
  'save': {
    outlineSvg: erpSaveOutline,
    filledSvg: erpSaveFilled,
    mirrorInRtl: false,
  },
  'upload': {
    outlineSvg: erpUploadOutline,
    filledSvg: erpUploadFilled,
    mirrorInRtl: false,
  },
  'download': {
    outlineSvg: erpDownloadOutline,
    filledSvg: erpDownloadFilled,
    mirrorInRtl: false,
  },
  'filter': {
    outlineSvg: erpFilterOutline,
    filledSvg: erpFilterFilled,
    mirrorInRtl: false,
  },
  'sort-ascending': {
    outlineSvg: erpSortAscendingOutline,
    filledSvg: erpSortAscendingFilled,
    mirrorInRtl: false,
  },
  'sort-descending': {
    outlineSvg: erpSortDescendingOutline,
    filledSvg: erpSortDescendingFilled,
    mirrorInRtl: false,
  },
  'more-horizontal': {
    outlineSvg: erpMoreHorizontalOutline,
    filledSvg: erpMoreHorizontalFilled,
    mirrorInRtl: false,
  },
  'more-vertical': {
    outlineSvg: erpMoreVerticalOutline,
    filledSvg: erpMoreVerticalFilled,
    mirrorInRtl: false,
  },
  'calendar': {
    outlineSvg: erpCalendarOutline,
    filledSvg: erpCalendarFilled,
    mirrorInRtl: false,
  },
  'clock': {
    outlineSvg: erpClockOutline,
    filledSvg: erpClockFilled,
    mirrorInRtl: false,
  },
  'lock': {
    outlineSvg: erpLockOutline,
    filledSvg: erpLockFilled,
    mirrorInRtl: false,
  },
  'unlock': {
    outlineSvg: erpUnlockOutline,
    filledSvg: erpUnlockFilled,
    mirrorInRtl: false,
  },
  'mail': {
    outlineSvg: erpMailOutline,
    filledSvg: erpMailFilled,
    mirrorInRtl: false,
  },
  'file': {
    outlineSvg: erpFileOutline,
    filledSvg: erpFileFilled,
    mirrorInRtl: false,
  },
  'folder': {
    outlineSvg: erpFolderOutline,
    filledSvg: erpFolderFilled,
    mirrorInRtl: false,
  },
  'attachment': {
    outlineSvg: erpAttachmentOutline,
    filledSvg: erpAttachmentFilled,
    mirrorInRtl: false,
  },
  'external-link': {
    outlineSvg: erpExternalLinkOutline,
    filledSvg: erpExternalLinkFilled,
    mirrorInRtl: false,
  },
  'help': {
    outlineSvg: erpHelpOutline,
    filledSvg: erpHelpFilled,
    mirrorInRtl: false,
  },
  'history': {
    outlineSvg: erpHistoryOutline,
    filledSvg: erpHistoryFilled,
    mirrorInRtl: false,
  },
  'undo': {
    outlineSvg: erpUndoOutline,
    filledSvg: erpUndoFilled,
    mirrorInRtl: false,
  },
  'redo': {
    outlineSvg: erpRedoOutline,
    filledSvg: erpRedoFilled,
    mirrorInRtl: false,
  },
  'plus': {
    outlineSvg: erpPlusOutline,
    filledSvg: erpPlusFilled,
    mirrorInRtl: false,
  },
  'minus': {
    outlineSvg: erpMinusOutline,
    filledSvg: erpMinusFilled,
    mirrorInRtl: false,
  },
};
