import {
  fluentAddCircle,
  fluentAlert,
  fluentArrowEnterLeft,
  fluentArrowSync,
  fluentBox,
  fluentBriefcase,
  fluentBuilding,
  fluentBuildingMultiple,
  fluentCall,
  fluentCheckmarkCircle,
  fluentChevronDown,
  fluentChevronLeft,
  fluentChevronRight,
  fluentChevronUp,
  fluentCopy,
  fluentDelete,
  fluentDismissCircle,
  fluentErrorCircle,
  fluentEye,
  fluentEyeOff,
  fluentGrid,
  fluentHandshake,
  fluentHome,
  fluentInfo,
  fluentLayer,
  fluentLocation,
  fluentMoneyHand,
  fluentNavigation,
  fluentNext,
  fluentPeople,
  fluentPerson,
  fluentPersonLock,
  fluentPrevious,
  fluentPrint,
  fluentSearch,
  fluentServer,
  fluentSettings,
  fluentShieldCheckmark,
  fluentSignOut,
  fluentWallet,
  fluentWeatherMoon,
  fluentWeatherSunny,
  fluentWifiOff,
  fluentWrench,
} from '@ng-icons/fluent-ui';
import {ErpIconName} from './icon-contracts';

export interface ErpIconDefinition {
  readonly svg: string;
  readonly mirrorInRtl: boolean;
}

export const ERP_ICON_REGISTRY: Readonly<Record<ErpIconName, ErpIconDefinition>> = {
  add: {svg: fluentAddCircle, mirrorInRtl: false},
  'chevron-down': {svg: fluentChevronDown, mirrorInRtl: false},
  'chevron-start': {svg: fluentChevronLeft, mirrorInRtl: true},
  'chevron-end': {svg: fluentChevronRight, mirrorInRtl: true},
  'chevron-up': {svg: fluentChevronUp, mirrorInRtl: false},
  branches: {svg: fluentBuildingMultiple, mirrorInRtl: false},
  building: {svg: fluentBuilding, mirrorInRtl: false},
  check: {svg: fluentCheckmarkCircle, mirrorInRtl: false},
  close: {svg: fluentDismissCircle, mirrorInRtl: false},
  copy: {svg: fluentCopy, mirrorInRtl: false},
  customer: {svg: fluentPerson, mirrorInRtl: false},
  dashboard: {svg: fluentGrid, mirrorInRtl: false},
  delete: {svg: fluentDelete, mirrorInRtl: false},
  error: {svg: fluentErrorCircle, mirrorInRtl: false},
  eye: {svg: fluentEye, mirrorInRtl: false},
  'eye-off': {svg: fluentEyeOff, mirrorInRtl: false},
  handshake: {svg: fluentHandshake, mirrorInRtl: false},
  home: {svg: fluentHome, mirrorInRtl: false},
  info: {svg: fluentInfo, mirrorInRtl: false},
  inventory: {svg: fluentBox, mirrorInRtl: false},
  layers: {svg: fluentLayer, mirrorInRtl: false},
  location: {svg: fluentLocation, mirrorInRtl: false},
  login: {svg: fluentArrowEnterLeft, mirrorInRtl: true},
  logout: {svg: fluentSignOut, mirrorInRtl: true},
  maintenance: {svg: fluentWrench, mirrorInRtl: false},
  menu: {svg: fluentNavigation, mirrorInRtl: false},
  money: {svg: fluentMoneyHand, mirrorInRtl: false},
  moon: {svg: fluentWeatherMoon, mirrorInRtl: false},
  notification: {svg: fluentAlert, mirrorInRtl: false},
  operations: {svg: fluentBriefcase, mirrorInRtl: false},
  people: {svg: fluentPeople, mirrorInRtl: false},
  phone: {svg: fluentCall, mirrorInRtl: false},
  'phone-call': {svg: fluentCall, mirrorInRtl: false},
  print: {svg: fluentPrint, mirrorInRtl: false},
  refresh: {svg: fluentArrowSync, mirrorInRtl: false},
  search: {svg: fluentSearch, mirrorInRtl: false},
  security: {svg: fluentPersonLock, mirrorInRtl: false},
  server: {svg: fluentServer, mirrorInRtl: false},
  settings: {svg: fluentSettings, mirrorInRtl: false},
  'shield-check': {svg: fluentShieldCheckmark, mirrorInRtl: false},
  'skip-start': {svg: fluentPrevious, mirrorInRtl: true},
  'skip-end': {svg: fluentNext, mirrorInRtl: true},
  success: {svg: fluentCheckmarkCircle, mirrorInRtl: false},
  sun: {svg: fluentWeatherSunny, mirrorInRtl: false},
  user: {svg: fluentPerson, mirrorInRtl: false},
  wallet: {svg: fluentWallet, mirrorInRtl: false},
  warning: {svg: fluentAlert, mirrorInRtl: false},
  'wifi-off': {svg: fluentWifiOff, mirrorInRtl: false},
};
