// Generated by tools/assets/manage-erp-avatar-library.mjs. Do not edit manually.
import type {ErpAvatarCatalogItem} from './avatar-picker-contracts';

export const ERP_AVATAR_CATALOG_GENERATED = Object.freeze(
  ([
  {
    "id": "avatar-01",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-01.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 1"
  },
  {
    "id": "avatar-02",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-02.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 2"
  },
  {
    "id": "avatar-03",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-03.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 3"
  },
  {
    "id": "avatar-04",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-04.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 4"
  },
  {
    "id": "avatar-05",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-05.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 5"
  },
  {
    "id": "avatar-06",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-06.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 6"
  },
  {
    "id": "avatar-07",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-07.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 7"
  },
  {
    "id": "avatar-08",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-08.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 8"
  },
  {
    "id": "avatar-09",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-09.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 9"
  },
  {
    "id": "avatar-10",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-10.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 10"
  },
  {
    "id": "avatar-11",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-11.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 11"
  },
  {
    "id": "avatar-12",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-12.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 12"
  },
  {
    "id": "avatar-13",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-13.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 13"
  },
  {
    "id": "avatar-14",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-14.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 14"
  },
  {
    "id": "avatar-15",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-15.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 15"
  },
  {
    "id": "avatar-16",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-16.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 16"
  },
  {
    "id": "avatar-17",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-17.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 17"
  },
  {
    "id": "avatar-18",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-18.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 18"
  },
  {
    "id": "avatar-19",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-19.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 19"
  },
  {
    "id": "avatar-20",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-20.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 20"
  },
  {
    "id": "avatar-male-021",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-021.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 21"
  },
  {
    "id": "avatar-male-022",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-022.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 22"
  },
  {
    "id": "avatar-male-023",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-023.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 23"
  },
  {
    "id": "avatar-male-024",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-024.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 24"
  },
  {
    "id": "avatar-male-025",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-025.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 25"
  },
  {
    "id": "avatar-male-071",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-071.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 71"
  },
  {
    "id": "avatar-male-072",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-072.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 72"
  },
  {
    "id": "avatar-male-073",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-073.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 73"
  },
  {
    "id": "avatar-male-074",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-074.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 74"
  },
  {
    "id": "avatar-male-075",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-075.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 75"
  },
  {
    "id": "avatar-male-076",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-076.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 76"
  },
  {
    "id": "avatar-male-077",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-077.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 77"
  },
  {
    "id": "avatar-male-078",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-078.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 78"
  },
  {
    "id": "avatar-male-079",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-079.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 79"
  },
  {
    "id": "avatar-male-080",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-080.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 80"
  },
  {
    "id": "avatar-male-081",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-081.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 81"
  },
  {
    "id": "avatar-male-082",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-082.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 82"
  },
  {
    "id": "avatar-male-083",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-083.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 83"
  },
  {
    "id": "avatar-male-084",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-084.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 84"
  },
  {
    "id": "avatar-male-085",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-085.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 85"
  },
  {
    "id": "avatar-male-086",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-086.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 86"
  },
  {
    "id": "avatar-male-087",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-087.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 87"
  },
  {
    "id": "avatar-male-088",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-088.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 88"
  },
  {
    "id": "avatar-male-089",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-089.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 89"
  },
  {
    "id": "avatar-male-090",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-090.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 90"
  },
  {
    "id": "avatar-male-091",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-091.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 91"
  },
  {
    "id": "avatar-male-102",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-102.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 102"
  },
  {
    "id": "avatar-male-103",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-103.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 103"
  },
  {
    "id": "avatar-male-104",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-104.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 104"
  },
  {
    "id": "avatar-male-105",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-105.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 105"
  },
  {
    "id": "avatar-male-106",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-106.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 106"
  },
  {
    "id": "avatar-male-107",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-107.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 107"
  },
  {
    "id": "avatar-male-108",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-108.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 108"
  },
  {
    "id": "avatar-male-109",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-109.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 109"
  },
  {
    "id": "avatar-male-110",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-110.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 110"
  },
  {
    "id": "avatar-male-111",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-111.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 111"
  },
  {
    "id": "avatar-male-112",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-112.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 112"
  },
  {
    "id": "avatar-male-113",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-113.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 113"
  },
  {
    "id": "avatar-male-114",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-114.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 114"
  },
  {
    "id": "avatar-male-115",
    "gender": "male",
    "imageUrl": "/assets/honesty-erp-avatars/users/male/avatar-male-115.png",
    "label": "صورة رمزية ثلاثية الأبعاد للرجال رقم 115"
  },
  {
    "id": "avatar-21",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-21.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 26"
  },
  {
    "id": "avatar-22",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-22.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 27"
  },
  {
    "id": "avatar-23",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-23.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 28"
  },
  {
    "id": "avatar-24",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-24.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 29"
  },
  {
    "id": "avatar-25",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-25.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 30"
  },
  {
    "id": "avatar-26",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-26.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 31"
  },
  {
    "id": "avatar-27",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-27.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 32"
  },
  {
    "id": "avatar-28",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-28.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 33"
  },
  {
    "id": "avatar-29",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-29.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 34"
  },
  {
    "id": "avatar-30",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-30.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 35"
  },
  {
    "id": "avatar-31",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-31.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 36"
  },
  {
    "id": "avatar-32",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-32.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 37"
  },
  {
    "id": "avatar-33",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-33.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 38"
  },
  {
    "id": "avatar-34",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-34.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 39"
  },
  {
    "id": "avatar-35",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-35.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 40"
  },
  {
    "id": "avatar-36",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-36.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 41"
  },
  {
    "id": "avatar-37",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-37.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 42"
  },
  {
    "id": "avatar-38",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-38.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 43"
  },
  {
    "id": "avatar-39",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-39.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 44"
  },
  {
    "id": "avatar-40",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-40.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 45"
  },
  {
    "id": "avatar-female-046",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-046.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 46"
  },
  {
    "id": "avatar-female-047",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-047.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 47"
  },
  {
    "id": "avatar-female-048",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-048.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 48"
  },
  {
    "id": "avatar-female-049",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-049.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 49"
  },
  {
    "id": "avatar-female-050",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-050.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 50"
  },
  {
    "id": "avatar-female-051",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-051.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 51"
  },
  {
    "id": "avatar-female-052",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-052.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 52"
  },
  {
    "id": "avatar-female-053",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-053.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 53"
  },
  {
    "id": "avatar-female-054",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-054.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 54"
  },
  {
    "id": "avatar-female-055",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-055.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 55"
  },
  {
    "id": "avatar-female-056",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-056.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 56"
  },
  {
    "id": "avatar-female-057",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-057.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 57"
  },
  {
    "id": "avatar-female-058",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-058.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 58"
  },
  {
    "id": "avatar-female-059",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-059.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 59"
  },
  {
    "id": "avatar-female-060",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-060.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 60"
  },
  {
    "id": "avatar-female-061",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-061.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 61"
  },
  {
    "id": "avatar-female-062",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-062.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 62"
  },
  {
    "id": "avatar-female-063",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-063.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 63"
  },
  {
    "id": "avatar-female-064",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-064.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 64"
  },
  {
    "id": "avatar-female-065",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-065.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 65"
  },
  {
    "id": "avatar-female-066",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-066.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 66"
  },
  {
    "id": "avatar-female-067",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-067.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 67"
  },
  {
    "id": "avatar-female-068",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-068.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 68"
  },
  {
    "id": "avatar-female-069",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-069.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 69"
  },
  {
    "id": "avatar-female-070",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-070.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 70"
  },
  {
    "id": "avatar-female-092",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-092.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 92"
  },
  {
    "id": "avatar-female-093",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-093.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 93"
  },
  {
    "id": "avatar-female-094",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-094.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 94"
  },
  {
    "id": "avatar-female-095",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-095.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 95"
  },
  {
    "id": "avatar-female-096",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-096.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 96"
  },
  {
    "id": "avatar-female-097",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-097.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 97"
  },
  {
    "id": "avatar-female-098",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-098.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 98"
  },
  {
    "id": "avatar-female-099",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-099.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 99"
  },
  {
    "id": "avatar-female-100",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-100.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 100"
  },
  {
    "id": "avatar-female-101",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-101.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 101"
  },
  {
    "id": "avatar-female-116",
    "gender": "female",
    "imageUrl": "/assets/honesty-erp-avatars/users/female/avatar-female-116.png",
    "label": "صورة رمزية ثلاثية الأبعاد للنساء رقم 116"
  }
] as const).map((item) => Object.freeze(item)),
) satisfies readonly ErpAvatarCatalogItem[];
