export const ERP_MOTION_PRESETS = [
  'fade',
  'scale',
  'fade-scale',
  'slide-up',
  'slide-down',
  'slide-start',
  'slide-end',
  'zoom',
  'pop',
  'flip-x',
  'flip-y',
  'bounce',
  'swing',
  'fade-up',
  'fade-down',
  'fade-start',
  'fade-end',
  'zoom-up',
  'zoom-down',
  'back',
  'light-speed',
  'rotate',
  'roll',
] as const;

export type ErpMotionPreset = (typeof ERP_MOTION_PRESETS)[number];
