// Generated by tools/foundation/generate-system-color-registry.mjs.
// Do not edit manually.

export const ERP_SYSTEM_COLOR_FAMILIES = [
  'neutral',
  'primary',
  'secondary',
  'accent',
  'green',
  'amber',
  'red',
  'cyan',
] as const;

export const ERP_SYSTEM_COLOR_STEPS = [
  50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950
] as const;

export type ErpSystemColorFamily =
  (typeof ERP_SYSTEM_COLOR_FAMILIES)[number];

export type ErpSystemColorStep =
  (typeof ERP_SYSTEM_COLOR_STEPS)[number];

export type ErpSystemColorToken =
  `${ErpSystemColorFamily}-${ErpSystemColorStep}`;

export const ERP_SYSTEM_COLOR_PALETTES = {
  neutral: {
    50: '#F8F9FB',
    100: '#F1F3F6',
    200: '#E3E6EC',
    300: '#C9CED8',
    400: '#989FAE',
    500: '#6F7584',
    600: '#545966',
    700: '#3C404B',
    800: '#272A32',
    900: '#181A20',
    950: '#101115',
  },
  primary: {
    50: '#EEF0FD',
    100: '#DCE0FA',
    200: '#BCC4F6',
    300: '#96A3F0',
    400: '#777FE1',
    500: '#5B61D5',
    600: '#494BC4',
    700: '#3B3BA4',
    800: '#2E2D82',
    900: '#232265',
    950: '#171645',
  },
  secondary: {
    50: '#F2F5FA',
    100: '#E5EBF5',
    200: '#CBD8EB',
    300: '#A5BDDD',
    400: '#7C9CCC',
    500: '#5F7FB8',
    600: '#4B659E',
    700: '#3F527F',
    800: '#374568',
    900: '#303B56',
    950: '#1D2536',
  },
  accent: {
    50: '#FBF1F8',
    100: '#F6E2F1',
    200: '#EDC5E4',
    300: '#DEA0D2',
    400: '#CA75BC',
    500: '#B154A4',
    600: '#943F89',
    700: '#79366F',
    800: '#62305A',
    900: '#512B4A',
    950: '#301529',
  },
  green: {
    50: '#EEFAF3',
    100: '#D9F3E3',
    200: '#B6E7C8',
    300: '#86D6A4',
    400: '#52BD7C',
    500: '#319F61',
    600: '#25804D',
    700: '#21663F',
    800: '#1E5135',
    900: '#1A432D',
    950: '#0D2519',
  },
  amber: {
    50: '#FFF8E8',
    100: '#FFEFC5',
    200: '#FFDE8B',
    300: '#FBC65A',
    400: '#F2AA2F',
    500: '#DF8F16',
    600: '#BD6F0F',
    700: '#95520F',
    800: '#793F13',
    900: '#653514',
    950: '#3A1B08',
  },
  red: {
    50: '#FFF1F1',
    100: '#FFE0DF',
    200: '#FFC4C2',
    300: '#FF9D99',
    400: '#F86F69',
    500: '#E84D47',
    600: '#C93833',
    700: '#A52E2A',
    800: '#882925',
    900: '#712724',
    950: '#3D1211',
  },
  cyan: {
    50: '#EEF9FC',
    100: '#D8F1F7',
    200: '#B5E3EF',
    300: '#82CFE1',
    400: '#4BB4CE',
    500: '#2B97B4',
    600: '#227992',
    700: '#216177',
    800: '#214F61',
    900: '#1F4352',
    950: '#102732',
  },
} as const satisfies Readonly<
  Record<ErpSystemColorFamily, Readonly<Record<ErpSystemColorStep, string>>>
>;

export function resolveErpSystemColorToken(
  token: ErpSystemColorToken,
): string {
  const separator = token.lastIndexOf('-');
  const family = token.slice(0, separator) as ErpSystemColorFamily;
  const step = Number(token.slice(separator + 1)) as ErpSystemColorStep;

  return ERP_SYSTEM_COLOR_PALETTES[family][step];
}
