// GENERATED by tools/catalog/erp-component-catalog.mjs. Do not edit by hand.
export interface ErpComponentNavigationEntry {
  readonly id: string;
  readonly className: string;
  readonly category: string;
  readonly showcaseRoute: string;
}

export const ERP_COMPONENT_NAVIGATION: readonly ErpComponentNavigationEntry[] = [
  {
    "id": "button",
    "className": "ErpButton",
    "category": "Actions",
    "showcaseRoute": "/components/button"
  },
  {
    "id": "button-group",
    "className": "ErpButtonGroup",
    "category": "Actions",
    "showcaseRoute": "/components/button-group"
  },
  {
    "id": "extended-fab",
    "className": "ErpExtendedFab",
    "category": "Actions",
    "showcaseRoute": "/components/extended-fab"
  },
  {
    "id": "fab",
    "className": "ErpFab",
    "category": "Actions",
    "showcaseRoute": "/components/fab"
  },
  {
    "id": "fab-menu",
    "className": "ErpFabMenu",
    "category": "Actions",
    "showcaseRoute": "/components/fab-menu"
  },
  {
    "id": "icon-button",
    "className": "ErpIconButton",
    "category": "Actions",
    "showcaseRoute": "/components/icon-button"
  },
  {
    "id": "split-button",
    "className": "ErpSplitButton",
    "category": "Actions",
    "showcaseRoute": "/components/split-button"
  },
  {
    "id": "app-shell",
    "className": "ErpAppShell",
    "category": "Application Shell",
    "showcaseRoute": "/components/app-shell"
  },
  {
    "id": "branch-selector",
    "className": "ErpBranchSelector",
    "category": "Application Shell",
    "showcaseRoute": "/components/branch-selector"
  },
  {
    "id": "global-search",
    "className": "ErpGlobalSearch",
    "category": "Application Shell",
    "showcaseRoute": "/components/global-search"
  },
  {
    "id": "notification-bell",
    "className": "ErpNotificationBell",
    "category": "Application Shell",
    "showcaseRoute": "/components/notification-bell"
  },
  {
    "id": "topbar",
    "className": "ErpTopbar",
    "category": "Application Shell",
    "showcaseRoute": "/components/topbar"
  },
  {
    "id": "user-menu",
    "className": "ErpUserMenu",
    "category": "Application Shell",
    "showcaseRoute": "/components/user-menu"
  },
  {
    "id": "bulk-action-bar",
    "className": "ErpBulkActionBar",
    "category": "Data / Tables",
    "showcaseRoute": "/components/bulk-action-bar"
  },
  {
    "id": "filter-bar",
    "className": "ErpFilterBar",
    "category": "Data / Tables",
    "showcaseRoute": "/components/filter-bar"
  },
  {
    "id": "filter-drawer",
    "className": "ErpFilterDrawer",
    "category": "Data / Tables",
    "showcaseRoute": "/components/filter-drawer"
  },
  {
    "id": "smart-table",
    "className": "ErpSmartTable",
    "category": "Data / Tables",
    "showcaseRoute": "/components/smart-table"
  },
  {
    "id": "table",
    "className": "ErpTable",
    "category": "Data / Tables",
    "showcaseRoute": "/components/table"
  },
  {
    "id": "table-toolbar",
    "className": "ErpTableToolbar",
    "category": "Data / Tables",
    "showcaseRoute": "/components/table-toolbar"
  },
  {
    "id": "alert",
    "className": "ErpAlert",
    "category": "Feedback / Status",
    "showcaseRoute": "/components/alert"
  },
  {
    "id": "empty-state",
    "className": "ErpEmptyState",
    "category": "Feedback / Status",
    "showcaseRoute": "/components/empty-state"
  },
  {
    "id": "skeleton",
    "className": "ErpSkeleton",
    "category": "Feedback / Status",
    "showcaseRoute": "/components/skeleton"
  },
  {
    "id": "status-badge",
    "className": "ErpStatusBadge",
    "category": "Feedback / Status",
    "showcaseRoute": "/components/status-badge"
  },
  {
    "id": "tooltip",
    "className": "ErpTooltip",
    "category": "Feedback / Status",
    "showcaseRoute": "/components/tooltip"
  },
  {
    "id": "entity-schema-fields",
    "className": "ErpEntitySchemaFields",
    "category": "Forms",
    "showcaseRoute": "/components/entity-schema-fields"
  },
  {
    "id": "form",
    "className": "ErpForm",
    "category": "Forms",
    "showcaseRoute": "/components/form"
  },
  {
    "id": "form-actions",
    "className": "ErpFormActions",
    "category": "Forms",
    "showcaseRoute": "/components/form-actions"
  },
  {
    "id": "form-section",
    "className": "ErpFormSection",
    "category": "Forms",
    "showcaseRoute": "/components/form-section"
  },
  {
    "id": "repeater",
    "className": "ErpRepeater",
    "category": "Forms",
    "showcaseRoute": "/components/repeater"
  },
  {
    "id": "standard-entity-form",
    "className": "ErpStandardEntityForm",
    "category": "Forms",
    "showcaseRoute": "/components/standard-entity-form"
  },
  {
    "id": "validation-summary",
    "className": "ErpValidationSummary",
    "category": "Forms",
    "showcaseRoute": "/components/validation-summary"
  },
  {
    "id": "color-picker",
    "className": "ErpColorPicker",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/color-picker"
  },
  {
    "id": "combo-box",
    "className": "ErpComboBox",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/combo-box"
  },
  {
    "id": "date-box",
    "className": "ErpDateBox",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/date-box"
  },
  {
    "id": "date-range-box",
    "className": "ErpDateRangeBox",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/date-range-box"
  },
  {
    "id": "date-time-box",
    "className": "ErpDateTimeBox",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/date-time-box"
  },
  {
    "id": "file-picker",
    "className": "ErpFilePicker",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/file-picker"
  },
  {
    "id": "icon-picker",
    "className": "ErpIconPicker",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/icon-picker"
  },
  {
    "id": "image-picker",
    "className": "ErpImagePicker",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/image-picker"
  },
  {
    "id": "item-picker",
    "className": "ErpItemPicker",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/item-picker"
  },
  {
    "id": "money-box",
    "className": "ErpMoneyBox",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/money-box"
  },
  {
    "id": "number-box",
    "className": "ErpNumberBox",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/number-box"
  },
  {
    "id": "number-stepper",
    "className": "ErpNumberStepper",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/number-stepper"
  },
  {
    "id": "password-box",
    "className": "ErpPasswordBox",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/password-box"
  },
  {
    "id": "range-slider",
    "className": "ErpRangeSlider",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/range-slider"
  },
  {
    "id": "search-box",
    "className": "ErpSearchBox",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/search-box"
  },
  {
    "id": "select",
    "className": "ErpSelect",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/select"
  },
  {
    "id": "tel-box",
    "className": "ErpTelBox",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/tel-box"
  },
  {
    "id": "text-area-box",
    "className": "ErpTextAreaBox",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/text-area-box"
  },
  {
    "id": "text-box",
    "className": "ErpTextBox",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/text-box"
  },
  {
    "id": "time-box",
    "className": "ErpTimeBox",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/time-box"
  },
  {
    "id": "url-box",
    "className": "ErpUrlBox",
    "category": "Inputs / Fields",
    "showcaseRoute": "/components/url-box"
  },
  {
    "id": "avatar",
    "className": "ErpAvatar",
    "category": "Media / Identity",
    "showcaseRoute": "/components/avatar"
  },
  {
    "id": "breadcrumbs",
    "className": "ErpBreadcrumbs",
    "category": "Navigation",
    "showcaseRoute": "/components/breadcrumbs"
  },
  {
    "id": "pagination",
    "className": "ErpPagination",
    "category": "Navigation",
    "showcaseRoute": "/components/pagination"
  },
  {
    "id": "sidebar",
    "className": "ErpSidebar",
    "category": "Navigation",
    "showcaseRoute": "/components/sidebar"
  },
  {
    "id": "sort-header",
    "className": "ErpSortHeader",
    "category": "Navigation",
    "showcaseRoute": "/components/sort-header"
  },
  {
    "id": "stepper",
    "className": "ErpStepper",
    "category": "Navigation",
    "showcaseRoute": "/components/stepper"
  },
  {
    "id": "tabs",
    "className": "ErpTabs",
    "category": "Navigation",
    "showcaseRoute": "/components/tabs"
  },
  {
    "id": "page",
    "className": "ErpPage",
    "category": "Page Composition",
    "showcaseRoute": "/components/page"
  },
  {
    "id": "page-header",
    "className": "ErpPageHeader",
    "category": "Page Composition",
    "showcaseRoute": "/components/page-header"
  },
  {
    "id": "page-shell",
    "className": "ErpPageShell",
    "category": "Page Composition",
    "showcaseRoute": "/components/page-shell"
  },
  {
    "id": "container",
    "className": "ErpContainer",
    "category": "Primitives",
    "showcaseRoute": "/components/container"
  },
  {
    "id": "divider",
    "className": "ErpDivider",
    "category": "Primitives",
    "showcaseRoute": "/components/divider"
  },
  {
    "id": "grid",
    "className": "ErpGrid",
    "category": "Primitives",
    "showcaseRoute": "/components/grid"
  },
  {
    "id": "icon",
    "className": "ErpIcon",
    "category": "Primitives",
    "showcaseRoute": "/components/icon"
  },
  {
    "id": "inline",
    "className": "ErpInline",
    "category": "Primitives",
    "showcaseRoute": "/components/inline"
  },
  {
    "id": "section",
    "className": "ErpSection",
    "category": "Primitives",
    "showcaseRoute": "/components/section"
  },
  {
    "id": "stack",
    "className": "ErpStack",
    "category": "Primitives",
    "showcaseRoute": "/components/stack"
  },
  {
    "id": "surface",
    "className": "ErpSurface",
    "category": "Primitives",
    "showcaseRoute": "/components/surface"
  },
  {
    "id": "text",
    "className": "ErpText",
    "category": "Primitives",
    "showcaseRoute": "/components/text"
  },
  {
    "id": "avatar-picker",
    "className": "ErpAvatarPicker",
    "category": "Selection",
    "showcaseRoute": "/components/avatar-picker"
  },
  {
    "id": "check-box",
    "className": "ErpCheckBox",
    "category": "Selection",
    "showcaseRoute": "/components/check-box"
  },
  {
    "id": "column-chooser",
    "className": "ErpColumnChooser",
    "category": "Selection",
    "showcaseRoute": "/components/column-chooser"
  },
  {
    "id": "radio-box",
    "className": "ErpRadioBox",
    "category": "Selection",
    "showcaseRoute": "/components/radio-box"
  },
  {
    "id": "radio-group",
    "className": "ErpRadioGroup",
    "category": "Selection",
    "showcaseRoute": "/components/radio-group"
  },
  {
    "id": "view-switcher",
    "className": "ErpViewSwitcher",
    "category": "Selection",
    "showcaseRoute": "/components/view-switcher"
  }
];
